targets:
  $default:
    builders:
      ferry_generator|graphql_builder:
        enabled: true
        options:
          schema: mobilizon_api|lib/schema.graphql
          fragments_glob: lib/graphql/fragments/**.graphql
          type_overrides:
            Upload:
              name: MultipartFile
              import: 'package:http/http.dart'
          
      ferry_generator|serializer_builder:
        enabled: true
        options:
          schema: mobilizon_api|lib/schema.graphql
          type_overrides:
            Upload:
              name: MultipartFile
              import: 'package:http/http.dart'
          custom_serializers:
            - import: "package:built_value/src/date_time_serializer.dart"
              name: DateTimeSerializer
