name: mobilizon_api
description: A Dart library for Mobilizon's authentication and profile management features.
version: 0.1.0
homepage: https://github.com/berkeleynerd/mobilizon_api
publish_to: none

environment:
  sdk: '>=3.8.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  meta: ^1.11.0
  gql_http_link: ^1.1.0
  # Upload media support 
  http: ^1.4.0
  http_parser: ^4.1.2
  mime: ^2.0.0
  path: ^1.9.1
  jwt_decoder: any

  built_value: any
  gql: any
  built_collection: any
  gql_exec: any
  gql_code_builder_serializers: any
  mobilizon_graphql_gen:
    path: /Users/rebecca/src/github.com/berkeleynerd/mobilizon_graphql_gen/
  ferry: any
dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  test: ^1.25.15
  build_runner: ^2.4.15

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec 
