name: mobilizon_api
description: A Dart library for Mobilizon's authentication and profile management features.
version: 0.1.0
homepage: https://github.com/berkeleynerd/mobilizon_api
publish_to: none

environment:
  sdk: '>=3.8.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  meta: ^1.11.0
  gql_http_link: ^1.1.0
  # Upload media support 
  http: ^1.4.0
  http_parser: ^4.1.2
  mime: ^2.0.0
  path: ^1.9.1
  jwt_decoder: any
  # GraphQL dependencies merged from mobilizon_graphql
  ferry: ^0.16.2-dev.4
  ferry_exec: any
  gql: ^1.0.0
  gql_exec: ^1.0.0
  # Command line parsing
  args: ^2.4.2
  # HTTP client for fetching GraphQL schemas
  # GraphQL and related dependencies
  gql_code_builder_serializers: any
  # Built Value for data classes
  built_value: ^8.7.0
  built_collection: ^5.1.1
  # Ferry dependencies
  ferry_flutter: ^0.9.1-dev.4
  ferry_hive_store: ^0.6.0+1
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  build_runner: ^2.4.7
  build_config: ^1.1.1
  built_value_generator: ^8.8.1
  ferry_generator: ^0.14.0-dev.0
  gql_code_builder: ^0.14.0
  lints: ^6.0.0
  test: ^1.25.15

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec 
